### ISSUE TITLE
What data structures can I have access to? 

### ISSUE THREAD

**Issue by nsathiya** [mark-archer/hostlang#2]
```
set var = [2, 3]
var[0] + var[1] 
```

Is this possible? Are array, maps, etc supported?

**Comment by mark-archer** [comment]
### The short answer
This can be done like this: (var is the name of the function used to declare a variable so I'm going to use myVar as the name instead)
```
var myVar : list 2 3
+ myVar.0 myVar.1
```

### The long answer
Host only has two data structures; Lists and Maps.  

You can declare a list with the `list` function or comma
```
var myList : list 2 3
var myList : , 2 3
var myList (list 2 3)
; the three lines above are all equivalent 
```

You can declare a map with the `new` function (maps and objects are synonymous in Host)
```
var myMap : new name="value" num=1 flag=true
```

accessing and assigning items in a list or fields in an object are done with dot notation
```
; get the first item in a list
myList.0 
; set the first item in a list to the value 5
set myList.0 5

; get the 'name' field from an object
myMap.name
; set the 'name' field to "new value"
set myMap.name "new value"
```

some list functions
```
; there are functions that enable lists to be processed in a function style instead of using dot notation
; gets the first item in the list
first myList

; gets a new list with everything but the first item in the list 
rest myList

; removes and returns an item from the front of the list (mutating it)
shift myList 

; removes and returns an item from the back of the list (mutating it)
pop myList

; adds an item to the front of the list and returns the list (mutating it)
unshift myList 5

; adds and item to the back of the list and returns the list (mutating it)
push myList 5
```

Host has some convenience logic built into it for negative indexes.
When a negative index is specified it will resolve to the length
of the list minus the value supplied. So -1 is the last item, -2 is 
the second to last, etc
```
; gets the last item in the list
myList.-1

; gets the second to last item in the index
myList.-2
```

Dot notation and variables.
With dot notation, it is often the case that you want to access a field or index using a variable name.
```
; in its simplest form, this is done with a leading backtick
; set the item at index 3 to 10
var i 4
set myList.`i 10
; the `i will be evaluated first and whatever it evaluates to will be the value used as the index (in this case 4)

; this works the same with maps
; this sets the 'name' field to "value3"
var fieldName "name"
set myMap.`fieldName "value3"

; this gets the value in the 'name' field
myMap.`fieldName

; expressions can also be supplied inside parenthesis to calculate the accessor name
var i 1
; this will return the item in myList at index 3
myList.(+ 2 i)
```

**Comment by nsathiya** [comment]
Thanks.
I am running into building this simple 'get sum of list' function. How do i set the upper limit for index using list length? list.length works. 


```
;; calculate sum of array
fn sumOfArray(input)
    var sum 0
    if input
    	var end input.length
    	for (i end): set sum (+ sum input.`i)
    log sum
var testArr : list 5 3

sumOfArray testArr
```
`Output: "NaN"`

And when should range be used?

**Comment by mark-archer** [comment]
for is inclusive of the upper limit (it should probably be changed to not
be inclusive) so

for(i 2)...

Is going to loop for i=0, i=1, and i=2. The list is undefined at i=2 so
adding that gives NaN


On May 31, 2017 11:54 PM, "Naren Sathiya" <notifications@github.com> wrote:

Thanks.
I am running into building this simple 'get sum of list' function. How do i
set the upper limit for index using list length? list.length works.

;; calculate sum of array
fn sumOfArray(input)
    var sum 0
    if input
    	var end input.length
    	for (i end): set sum (+ sum input.`i)
    log sum
var testArr : list 5 3

sumOfArray testArr

Output: "NaN"

And when should range be used?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/mark-archer/hostlang/issues/2#issuecomment-305405364>,
or mute the thread

**Comment by mark-archer** [comment]
range just returns a list of numbers. This is usually used in conjunction
with each and map.

map (range 10) n: ... ; do something

**Comment by nsathiya** [comment]
Ah yea it does. I recognized it was inclusive but was trying input.length-1 and it gave me an error. Thanks issue resolved!

**Comment by mark-archer** [comment]
Yeah, I also forget and use infix notation all the time.  I think it's the main reason more people don't use Lisp-like languages.  Infix feels so much more natural with the basic operators.  Because of this and the awkwardness of prefix notation with boolean expressions, I'm going to write a parser for `&`, `|`, `&&`, `||`, `+`, `-`, `*`, and `/`.

The parser is just going to check to see if there is one of those symbols in the second position of a list and if so, it's going to swap it with the item in the first position.  
```
; so this 
input.length - 1
; will result in the same parsed expression as this
- input.length 1

; there will need to be some added logic for chaining but I think it can be done pretty 
; easily as long as operator precedence isn't a concern

; so this 
1 + 2 * 3 / 4
; would get parsed into this
/ (* (+ 1 2) 3) 4
```

The only downside is it might cause confusion as to when infix is allowed and when prefix is required.  This possible confusion and inconsistency have been what's kept me from writing the parsers before now but as I've been using the language to do real work, I've really noticed how awkward prefix is with boolean expressions.
```
(a && b || c) || d || (e && f)
; vs
|| (|| (&& a b) c) d (&& e f)
```
That second form just looks ugly and hard to read to me. I find I write it out in the first form and then translate it to the second one for anything more complicated than a single && or ||.  Perhaps this is because I have the first form so ingrained but I don't think so.  I think the way people reason through a boolean expression is in the infix form, "It should be `a` and `b`, or `c`, or if that's all false, it should be `d` or `e` and `f`".  If I'm right about this then people will forever have to be jumping back to the front of the expression to add the next operator as they think of it.  It's annoying enough to make people use a different language.  So I'm going to write the parser.

I'm curious to know what you think.  Do you think it's totally distracting to have to write out a boolean expression in prefix notation?  Or do you think it's just a matter of preference/experience which form is used?

**Comment by nsathiya** [comment]
Sure, for the average user, infix notation has better readability. Most will need some time to get adjusted to prefix notation. 

How are you planning on implementing it? Also, I will assume paranthesis will be supported to specify ordering? (Since pre/post fix inherently solves this)

**Comment by mark-archer** [comment]
Yeah, parentheses are always supported and recommended when in doubt.

**Comment by nsathiya** [comment]
So if you were to implement the infix structure, prefix should be disabled then? Is there a reason prefix will be easier/more suitable than infix? Both shouldn't be combined right?

**Comment by mark-archer** [comment]
I was actually planning on leaving the prefix functionality.  So both these would work:
```
+ 1 2
1 + 2
```
Since one of the most important rules in Host is "the first item in a list is always a function", I don't want to make an exception to it as I think that would cause even more confusion and provide no real benefit. 

As an aside, when I consider adding or removing some feature or functionality I try to follow Paul Graham's advice in one of his essays (I think on Arc but I can't remember which one: http://www.paulgraham.com/arc.html).  He says, at one point that, unless there is a tangible reason why a feature or functionality should be removed, it should be left it.  He asserts that there are lots of language designs that purposefully limit the programmer "to protect them".  He often cites Java.  He says this is a counterproductive thing to do because bad programmers will always find a way to shoot themselves in the foot so all that's being done is taking an option away from good programmers.  I couldn't agree with him more.
