### ISSUE TITLE
List Documentation

### ISSUE THREAD

**Issue by devon-stanley** [mark-archer/hostlang#5]
Probably need to add some additional documentation for accessing list members (indexing) as well as list properties (i.e. length, indexOf, etc.)

Additional Questions:
- How to access members of a 2d array (I tried with array.index.subindex but that didn't work)
- Is there a list constructor for large lists with default values (e.g creating a list of 100 elements with a default value of 3)

**Comment by mark-archer** [comment]
Thanks for the suggestion.  I added some documentation here: https://github.com/mark-archer/hostlang/tree/UBO#property-accessors Let me know if it's sufficient. 

You were correct in trying array.index.subindex.  Unfortunately there's a bug in the parser which sees that as a floating point number instead of a nested accessor.  This is high on my priority list to fix.  For now you can get around this by wrapping each index in double quotes like so: 
    
    lst."0"."1"   

There's no built in function to instantiate a list of n items with some default value but you can do it pretty easily with `range` and `each`. Something like this:
```
; create a list of 100 items all defaulted to 1
each (range 100) n : 1
```

**Comment by mark-archer** [comment]
I've fixed that bug now so `lst.0.1` should work fine now
